### ISSUE TITLE
V2

### ISSUE THREAD

**Issue by boelle** [MartinD-CZ/batteryCharger#1]
Hi

have you started on V2 ?

I was looking for a charger most like yours, but have ideas for extra features

I have one of these old car chargers that can output about 15A.. would it be easy to expand the charger so it could go this high?

and if we fit one of those full graphics displays we would have a more space plus we could log things to a sd card?

just thoughts

**Comment by boelle** [comment]
i read a bit about desulfators, they are great for car batteries that are going bad, sometimes you can bring them to life

and interesting a few people on the internet have used them with nimh cell's too

this one looks interesting: http://www.instructables.com/id/Desulfator-for-12V-Car-Batteries-in-an-Altoids-Ti/

more simple schematic here: https://www.circuitlab.com/editor/#?id=yr82k8

**Comment by MartinD-CZ** [comment]
Hi,

well, version 2 is scheduled, but I am currently very busy, so I think it
will not be out before the end od February. Well, theoretically it is only
a matter of changing components and their values for this thing to output
15A, but I have never tried more than 5A...
Well, of course, a better display would be a fine addition. But I was going
for as-cheap-as-possible, and I think that enough information fits on the
screen.

Regards,
Martin

**Comment by boelle** [comment]
oki, could you put a reply more in here when you are about to publish it?

i might want to draw it in eagle schematic and do a real pcb of it.

would the desulfator idea be bad? and can it still fit on the same screen?

**Comment by boelle** [comment]
oh.. i forgot... for the first version i see that you used eagle schematic also

how far have you come with V2? do you need to draw it first?

and also have you published the files for v1.3 ?

**Comment by MartinD-CZ** [comment]
Hi,

as far as version 2 goes, I have the product working, what remains is
drawing the schematics, proper PCB layout and all the documentation. As for
the desulfator, I will have a look at it tomorrow, today I am busy.

Martin.

**Comment by boelle** [comment]
np... cant wait to see what you have come up with :-D

**Comment by sjdaliyan** [comment]
Any news of v2?

**Comment by MartinD-CZ** [comment]
Hi,

well, I din't advance on it much. I have the board drawn, and manufactured,
but I did not get the time to populate, test, program and write about it.
So for now, the project is on hold, as I am working on different projects
now...
If I ever get back to it (and I want, don't get me wrong), I will certainly
publish it... But I do not have a clue as to when that might be.

Regards,
Martin

**Comment by goosenphil** [comment]
Hi, since you've drawn the schematic in order to make the PCB, could you share the schematic and code with us in the meantime?

Since this is an open source project, some of us can take on the tasks you have not been able to reach.

It's fine if it's unfinished, we just want to see what you have so far.
